spring.application.name=visitas

# conexão com banco
spring.datasource.url=jdbc:mysql://localhost:3306/visitas_db
spring.datasource.username=root
spring.datasource.password=#Ronaldo7662#

# driver mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# jpa / hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true